language: python

cache: pip

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      dist: xenial
      env: TOXENV=py37
    - python: 3.8-dev
      dist: xenial
      env: TOXENV=py38

    - python: 3.6
      dist: xenial
      env: TOXENV=build

os:
  - linux

install:
  - travis_retry bash -x .travis/install.sh

script:
  - bash -x .travis/run_test.sh

notifications:
  slack:
    secure: LqMd2Ddk+yY3pyRumasqMH3cpRrD0h5CvmhWHqT1PFFm9UA8bLpgf9gOfSN5n/BO60AD0Wr68fJOzvFbC5U4D4x7dcDHEPPWIDHBKPaO++tjITdcxbvOsiUySAc0VPm0JqMpiv/x2JLYiqhf9PRNJgnF8HdBrqmUioj6RZHabqpvkmq9HocmFCNeVOHPqQjBXMmo3eXuc5eRCJxG053f+sPDFwXHjYggMXFXasghPFAqWQRthPN4bqD0abTgUfIYxsgr2Gtx7e21Jp+lraPTcGWnXdco1d81WG+FMLFx6weLgTaw1Fp/T6bs5+fnC2e3bj92BrvSOM3NLLXvn2iOXW1R2nOfXlC10XQuz2UDIbUKdXxgF64F/Lpd2mlTrBgFCl4eLRaVgK1wdsIVvEf/stiXu4v5bIde2UTtimUeKUYbmX05FN5KVh7kQIdwBndJwkOXk+VWs4u1ynfw64upRbFihVBVqbarB8bjnwjVNDbpfF2xTTUjT4sZdPg2YCcBVVnrMbYGNIiDjPgWpLE0VB85dgFEADltkE0kZSbyn13d8kj8jS6+pZ+tNI6oACB0C0e5O+Sy+XozIQ4W5UhXJ2O424fAhNpO0aoqWAUHLTSSzEjiPib2LkJD9siD3GW7GM22rbFxMiIJ2eFCFclKzFxtaVj6czUH4yLk8VtAlNk=

before_deploy:
  - bash -x build_package.sh

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "WM4FcDAD+QLP6+fgmDimd48PHJb+tr+0K6N6jNIdnh8TkQjLn5f/MJiu8UXW+J6wTDWgHKGlmC71xS8K2qNmp/lkrzRAHO7wSSNo9aeAFqFT1k/d0lmORmHvtIHQUO5S7VZFEQ2FeUFlXp0gV2ulpIdnZQHPZkDL75ioQfMIlBYLogiRs/rq/o7Si63rKAIVrT5sGYPaO47LXNaADqpGv7zBS07zsQCUgUwy5qwPEhCG+jPSesPJ5RVoegjUMon2zrT0k+iX6LiMAUnyUL+bkrqsn2eX+lonVSKQ9qSqXQhGPTirEHmGGAmNe6LmYrVHcABR7Dw5/Ea2CqwQU9PDPKYDgrevBiy2evyocv1I65d4Ry7vEX7/Gbj/ez81IBU4R/O/Br4Ik5F+NAw3N0OVrunsliy0IYDBoWy8k782oX9qSq0gWKTmIyTUhFh7yhpaJgmP4bvA+v9EJ6uv1NzTX0tQIFzeT0lAJSic3d8y7jyYQc77uQW2gHrv4i2M20sH5IHbud7jDq176eJvn5qLzCQOcTg4F8hz5s0A+p2Vm3t7pyCGtFXhkiQB9SA9d6flZ/uM3uhK9GxI9M7cQNPJ5IzSqcLGIWDkoGmVopklzoDafurYFDYPmTTbMhh6JP9BIeP0KgpfaYb/lRsNAh9l5sAw1570sOpVCJXqzFF+Jis="
    file_glob: true
    file: 'dist/tcconfig_*.deb'
    on:
      tags: true
      branch: master
      condition: "$TOXENV = build"
